name: Girls Who Code Bothell
author: GWC Bothell
description: Girls Who Code at the Bothell, WA Library is an after school club that teaches computer science to 6th-12th grade girls.

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
